$(document).ready(function(){
$(".A").hover(function(){
  $(".Jimmy").slideToggle()
});
$(".B").hover(function(){
  $(".yellow").slideToggle()
});
$(".C").hover(function(){
  $(".Mighty").slidetoggle()
});
$(".D").hover(function(){
  $(".BlackDark").slideToggle()
});
$(".E").hover(function(){
  $(".Happy").fadeToggle()
});
$(".F").hover(function(){
  $(".Settings").fadeToggle()
});
$(".G").hover(function(){
  $(".Burned").fadeToggle()
});
$(".H").hover(function(){
  $(".Giraffe").fadeToggle()
});
$(".design,#design").click(function(){
  $("#design,.design").fadeToggle()
});
});
